#!/usr/bin/env python3
"""Vendor the app's webfonts locally.

The app must render identically with no third-party network calls: a CDN <link> leaks
every visitor to fonts.gstatic.com and makes the page fail closed when offline (the
service worker can't cache a cross-origin opaque response reliably). So we download
the woff2 files once, commit them, and ship a local @font-face sheet.

Only the `latin` and `latin-ext` subsets are kept — the Cyrillic/Greek/Vietnamese
subsets Google serves trebles the byte count for glyphs this UI never renders.

Run from the repo root:  python tools/fetch-fonts.py
Regenerates: client/public/fonts/*.woff2 and client/public/fonts/fonts.css
"""
import re
import pathlib
import urllib.request

CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Inter:wght@400;500;600;700"
    "&family=JetBrains+Mono:wght@400;500;600"
    "&display=swap"
)
# Google returns woff2 only when it believes the client supports it.
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
KEEP_SUBSETS = {"latin", "latin-ext"}

OUT_DIR = pathlib.Path(__file__).resolve().parent.parent / "client" / "public" / "fonts"


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    css = fetch(CSS_URL).decode("utf-8")

    # Google emits `/* subset */` immediately before each @font-face block it labels.
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)
    if not blocks:
        raise SystemExit("no @font-face blocks parsed — did the CSS format change?")

    out_css: list[str] = [
        "/* Self-hosted webfonts — generated by tools/fetch-fonts.py, do not edit by hand.",
        "   Vendored so the app makes zero third-party requests and works offline. */",
        "",
    ]
    seen: set[str] = set()
    kept = 0

    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not m:
            continue
        url = m.group(1)

        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        filename = f"{family.lower().replace(' ', '-')}-{weight}-{subset}.woff2"

        if filename not in seen:
            (OUT_DIR / filename).write_bytes(fetch(url))
            seen.add(filename)
            print(f"  fetched {filename}")

        # Rewrite to a root-relative-to-the-stylesheet path so it survives the
        # /elegant-joins/ Pages base path without any build-time substitution.
        out_css.append(block.replace(f"url({url})", f"url(./{filename})").strip())
        out_css.append("")
        kept += 1

    (OUT_DIR / "fonts.css").write_text("\n".join(out_css), encoding="utf-8")
    total = sum(f.stat().st_size for f in OUT_DIR.glob("*.woff2"))
    print(f"\n{kept} @font-face rules, {len(seen)} files, {total / 1024:.0f} KB -> {OUT_DIR}")


if __name__ == "__main__":
    main()
